import dev1 from './devpng.png'
import dev2 from './dev2png.png'
import workpng from './workpng.png'
import aboutme from './aboutmepng.png'
import dream1 from './dream1.jpg'
import dream2 from './dream2.jpg'
import dream3 from './dream3.jpg'
import dream4 from './dream4.jpg'
import netflix1 from './netflix1.jpg'
import netflix2 from './netflix2.jpg'
import netflix3 from './netflix3.jpg'
import nike from './nike.jpg'
import nike1 from './nike1.jpg'
import nike2 from './nike2.jpg'
import nike3 from './nike3.jpg'
import global from './global.jpg'
import global1 from './global.jpg'
import global2 from './global2.jpg'
import global3 from './global3.jpg'

export {dev1, dev2, workpng, aboutme,dream1,dream2,dream3,dream4,netflix1,netflix2,netflix3,nike,nike1,nike2,nike3,global,global1,global2,global3}